import { useState, useRef } from 'react';
import { Copy, Trash2, Download, Check, Save, FileText, Printer } from 'lucide-react';
import { Tool } from '../types';
import { jsPDF } from 'jspdf';

interface OutputViewProps {
  tool: Tool;
  output: string;
  onClear: () => void;
  isLoading: boolean;
  historyId?: string;
  onSaveOutputToHistory?: () => void;
  t: any;
}

export default function OutputView({ 
  tool, 
  output, 
  onClear, 
  isLoading,
  historyId,
  onSaveOutputToHistory,
  t
}: OutputViewProps) {
  const [copied, setCopied] = useState(false);
  const [saved, setSaved] = useState(false);
  const outputRef = useRef<HTMLDivElement>(null);

  const handleCopy = async () => {
    if (!output) return;
    try {
      await navigator.clipboard.writeText(output);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy text: ', err);
    }
  };

  const handleExportTxt = () => {
    if (!output) return;
    const element = document.createElement('a');
    const file = new Blob([output], { type: 'text/plain;charset=utf-8' });
    element.href = URL.createObjectURL(file);
    element.download = `AI_Hub_${tool.id}_${Date.now()}.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const handleExportPdf = () => {
    if (!output) return;
    try {
      const doc = new jsPDF({
        orientation: 'p',
        unit: 'mm',
        format: 'a4',
      });
      
      const title = tool.title || 'AI Output';
      const cleanText = output.replace(/\*\*/g, ''); // strip markdown bold stars for raw pdf
      const lines = doc.splitTextToSize(cleanText, 180);
      
      let y = 20;
      doc.setFont("Helvetica", "normal");
      doc.setFontSize(14);
      doc.text(title, 15, y);
      
      y += 10;
      doc.setFontSize(10);
      lines.forEach((line: string) => {
        if (y > 280) {
          doc.addPage();
          y = 15;
        }
        doc.text(line, 15, y);
        y += 7;
      });
      
      doc.save(`AI_Hub_${tool.id}_${Date.now()}.pdf`);
    } catch (err) {
      console.error("PDF generation failed:", err);
    }
  };

  const handlePrintPdf = () => {
    if (!output) return;
    
    // Create iframe elements dynamically
    const iframe = document.createElement('iframe');
    iframe.style.position = 'fixed';
    iframe.style.right = '0';
    iframe.style.bottom = '0';
    iframe.style.width = '0';
    iframe.style.height = '0';
    iframe.style.border = 'none';
    document.body.appendChild(iframe);
    
    const doc = iframe.contentWindow?.document || iframe.contentDocument;
    if (!doc) return;
    
    const isEnglish = tool.id.includes('en') || tool.id.includes('translate_to') || tool.id.includes('write_email') || tool.id.includes('code');
    const currentDirection = isEnglish ? 'ltr' : 'rtl';
    const subTitleText = isEnglish 
      ? `Generated by AI Tools Hub - ${new Date().toLocaleDateString()}` 
      : `تصدير ذكي من منصة الأدوات والذكاء الاصطناعي العربية - ${new Date().toLocaleDateString()}`;
    const footerText = isEnglish 
      ? `Processed and exported with AI © ${new Date().getFullYear()} All rights reserved.` 
      : `تمت معالجة المستند وتصديره بواسطة الذكاء الاصطناعي © ${new Date().getFullYear()} جميع الحقوق محفوظة.`;

    const htmlContent = `
      <!DOCTYPE html>
      <html dir="${currentDirection}">
      <head>
        <meta charset="utf-8">
        <title>${tool.title}</title>
        <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;800&family=Inter:wght@400;600;800&display=swap" rel="stylesheet">
        <style>
          body {
            font-family: 'Cairo', 'Inter', sans-serif;
            padding: 40px;
            color: #1e293b;
            line-height: 1.8;
            background: #ffffff;
            direction: ${currentDirection};
          }
          .header {
            border-bottom: 2px solid #e2e8f0;
            padding-bottom: 12px;
            margin-bottom: 24px;
            display: flex;
            flex-direction: column;
            gap: 4px;
          }
          .title {
            font-size: 22px;
            font-weight: 800;
            color: #1d4ed8;
            margin: 0;
          }
          .subtitle {
            font-size: 12px;
            color: #64748b;
            margin: 0;
          }
          .content {
            font-size: 14px;
            white-space: pre-wrap;
            color: #334155;
          }
          .footer {
            margin-top: 50px;
            border-top: 1px solid #e2e8f0;
            padding-top: 15px;
            font-size: 10px;
            color: #94a3b8;
            text-align: center;
          }
          p {
            margin-bottom: 12px;
          }
          strong {
            color: #0f172a;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1 class="title">${tool.title}</h1>
          <p class="subtitle">${subTitleText}</p>
        </div>
        <div class="content">
          ${outputRef.current ? outputRef.current.innerHTML : output}
        </div>
        <div class="footer">
          ${footerText}
        </div>
      </body>
      </html>
    `;
    
    doc.write(htmlContent);
    doc.close();
    
    setTimeout(() => {
      iframe.contentWindow?.focus();
      iframe.contentWindow?.print();
      setTimeout(() => {
        document.body.removeChild(iframe);
      }, 1000);
    }, 450);
  };

  const handleSaveLocally = () => {
    if (onSaveOutputToHistory) {
      onSaveOutputToHistory();
      setSaved(true);
      setTimeout(() => setSaved(false), 2000);
    }
  };

  // Simple and beautiful Markdown Formatter
  const renderFormattedOutput = (text: string) => {
    if (!text) return null;

    const lines = text.split('\n');
    return lines.map((line, idx) => {
      let trimmedLine = line.trim();

      // Horizontal dividers
      if (trimmedLine === '---' || trimmedLine === '***') {
        return <hr key={idx} className="my-4 border-slate-100 dark:border-slate-800" />;
      }

      // Headers (e.g., ### title, ## title, # title)
      const headerMatch = trimmedLine.match(/^(#{1,6})\s+(.*)$/);
      if (headerMatch) {
        const level = headerMatch[1].length;
        const headerText = headerMatch[2];
        if (level === 1) {
          return <h3 key={idx} className="text-xl lg:text-2xl font-black text-amber-600 dark:text-amber-400 mt-6 mb-3">{headerText}</h3>;
        } else if (level === 2) {
          return <h4 key={idx} className="text-lg lg:text-xl font-bold text-slate-900 dark:text-white mt-5 mb-2">{headerText}</h4>;
        } else {
          return <h5 key={idx} className="text-base lg:text-lg font-bold text-slate-800 dark:text-slate-200 mt-4 mb-2">{headerText}</h5>;
        }
      }

      // Check lists (e.g., - item or * item)
      const listMatch = trimmedLine.match(/^[-*+]\s+(.*)$/);
      if (listMatch) {
        return (
          <li key={idx} className="flex items-start gap-2 text-slate-700 dark:text-slate-300 mr-4 mb-1.5 list-none leading-relaxed text-sm">
            <span className="text-amber-500 mt-1.5 shrink-0 block w-1.5 h-1.5 rounded-full" />
            <span dangerouslySetInnerHTML={{ __html: processInlineStyle(listMatch[1]) }} />
          </li>
        );
      }

      // Bolded paragraphs and custom bold process
      if (trimmedLine === '') {
        return <div key={idx} className="h-2" />;
      }

      return (
        <p 
          key={idx} 
          className="text-slate-700 dark:text-slate-300 leading-relaxed text-sm mb-2"
          dangerouslySetInnerHTML={{ __html: processInlineStyle(trimmedLine) }}
        />
      );
    });
  };

  // Helper function to turn **text** into <strong>text</strong>
  const processInlineStyle = (text: string) => {
    let html = text
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;");
    
    // Bold replaces
    html = html.replace(/\*\*(.*?)\*\*/g, '<strong class="font-bold text-slate-900 dark:text-white">$1</strong>');
    
    // Inline code
    html = html.replace(/`(.*?)`/g, '<code class="px-1.5 py-0.5 bg-slate-100 dark:bg-slate-800 text-xs rounded font-mono text-orange-500 dark:text-amber-400">$1</code>');
    
    // Basic Sanitization to prevent XSS while allowing our generated tags
    const tempDiv = document.createElement('div');
    tempDiv.innerHTML = html;
    const scripts = tempDiv.getElementsByTagName('script');
    for (let i = scripts.length - 1; i >= 0; i--) {
      scripts[i].parentNode?.removeChild(scripts[i]);
    }
    const attributes = ['onmouseover', 'onclick', 'onerror', 'onload'];
    const allElements = tempDiv.getElementsByTagName('*');
    for (let i = 0; i < allElements.length; i++) {
      for (let j = 0; j < attributes.length; j++) {
        allElements[i].removeAttribute(attributes[j]);
      }
    }
    
    return tempDiv.innerHTML;
  };

  return (
    <div id="result-view-container" className="bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-3xl overflow-hidden shadow-sm flex flex-col h-full min-h-[200px] sm:min-h-[300px] lg:min-h-[400px]">
      {/* Header bar */}
      <div className="bg-slate-50 dark:bg-slate-950/40 px-3 sm:px-6 py-2 sm:py-4 border-b border-slate-100 dark:border-slate-800/60 flex flex-row items-center justify-between gap-2">
        <h3 className="font-bold text-[11px] sm:text-sm text-slate-700 dark:text-slate-300 whitespace-nowrap">
          {'النتيجة والإنتاج الذكي'}
        </h3>
        
        {output && !isLoading && (
          <div className="flex items-center gap-1 overflow-x-auto flex-nowrap" style={{ scrollbarWidth: 'none' }}>
            <button
              id="output-btn-copy"
              onClick={handleCopy}
              title={t.copyCode}
              className="p-2 text-slate-500 dark:text-slate-400 hover:bg-white dark:hover:bg-slate-900 rounded-xl hover:text-blue-500 dark:hover:text-blue-400 transition-all border border-transparent hover:border-slate-100 dark:hover:border-slate-800 cursor-pointer"
            >
              {copied ? <Check size={16} className="text-emerald-500" /> : <Copy size={16} />}
            </button>
            
            {/* Quick RAW TXT Export */}
            <button
              id="output-btn-export-txt"
              onClick={handleExportTxt}
              title="تصدير ملف نصوص TXT"
              className="p-2 text-slate-500 dark:text-slate-400 hover:bg-white dark:hover:bg-slate-900 rounded-xl hover:text-blue-500 dark:hover:text-blue-400 transition-all border border-transparent hover:border-slate-100 dark:hover:border-slate-800 cursor-pointer"
            >
              <Download size={16} />
            </button>

            {/* Quick jsPDF program download */}
            <button
              id="output-btn-export-pdf"
              onClick={handleExportPdf}
              title={t.exportPdf}
              className="p-2 text-slate-500 dark:text-slate-400 hover:bg-white dark:hover:bg-slate-900 rounded-xl hover:text-amber-500 dark:hover:text-amber-400 transition-all border border-transparent hover:border-slate-100 dark:hover:border-slate-800 cursor-pointer"
            >
              <FileText size={16} />
            </button>

            {/* Precision Cairo/Inter Styled PDF Document Print */}
            <button
              id="output-btn-print-pdf"
              onClick={handlePrintPdf}
              title={t.printPdf}
              className="p-2 text-slate-500 dark:text-slate-400 hover:bg-white dark:hover:bg-slate-900 rounded-xl hover:text-emerald-500 dark:hover:text-emerald-400 transition-all border border-transparent hover:border-slate-100 dark:hover:border-slate-800 cursor-pointer"
            >
              <Printer size={16} />
            </button>

            <button
              id="output-btn-save"
              onClick={handleSaveLocally}
              disabled={saved}
              title="حفظ محلي في السجل"
              className="p-2 text-slate-500 dark:text-slate-400 hover:bg-white dark:hover:bg-slate-900 rounded-xl hover:text-blue-500 dark:hover:text-blue-400 transition-all border border-transparent hover:border-slate-100 dark:hover:border-slate-800 cursor-pointer disabled:opacity-50"
            >
              {saved ? <Check size={16} className="text-emerald-500" /> : <Save size={16} />}
            </button>
            <div className="w-px h-5 bg-slate-200 dark:bg-slate-800 mx-1" />
            <button
              id="output-btn-clear"
              onClick={onClear}
              title="مسح النتيجة"
              className="p-2 text-rose-500 hover:bg-rose-50 dark:hover:bg-rose-950/20 rounded-xl transition-all cursor-pointer"
            >
              <Trash2 size={16} />
            </button>
          </div>
        )}
      </div>

      {/* Main output content area */}
      <div className="flex-1 p-6 lg:p-8 overflow-y-auto">
        {isLoading ? (
          <div className="flex flex-col items-center justify-center h-full gap-4 text-center py-12">
            <div className="relative w-16 h-16">
              <div className="absolute inset-0 rounded-full border-4 border-amber-500/20 animate-pulse" />
              <div className="absolute inset-0 rounded-full border-4 border-amber-500 border-t-transparent animate-spin" />
            </div>
            <div>
              <h4 className="font-bold text-slate-900 dark:text-slate-100 text-base animate-pulse">{'شحذ خلايا الذكاء الاصطناعي...'}</h4>
              <p className="text-xs text-slate-500 dark:text-slate-400 mt-1 max-w-xs mx-auto">{'نقوم بصياغة استجابة مخصصة وراقية لطلبك الآن، يرجى الصبر ثوانٍ قليلة.'}
              </p>
            </div>
          </div>
        ) : output ? (
          <div 
            ref={outputRef}
            className="prose dark:prose-invert max-w-none"
          >
            {renderFormattedOutput(output)}
          </div>
        ) : (
          <div className="flex flex-col items-center justify-center h-full text-center py-16 px-4">
            <div className="p-4 bg-slate-50 dark:bg-slate-950/40 border border-slate-100 dark:border-slate-800 rounded-3xl text-slate-300 dark:text-slate-700 mb-4 animate-bounce">
              <Download size={36} />
            </div>
            <h4 className="font-bold text-slate-700 dark:text-slate-300 text-sm">
              {tool.id.includes('en') || tool.id.includes('translate_to') ? 'Ready to Generate!' : 'مستعد للبدء بالتوليد!'}
            </h4>
            <p className="text-xs text-slate-400 dark:text-slate-500 max-w-xs mt-1 leading-relaxed">
              {tool.id.includes('en') || tool.id.includes('translate_to') ? 'Fill in the required inputs on the left and click "Start Processing".' : 'قم بملء البيانات المطلوبة في النموذج الجانبي، واضغط على "ابدأ التوليد الذكي" لعرض النتيجة هنا فوراً.'}
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
